CREATE PROCEDURE [dbo].[RET_VIEWS_BYROLE_PR]
  @P_USER_ID INT
AS
BEGIN
Select V.CONTENT, V.TITLE from dbo.[USERS]
  INNER JOIN [dbo].[ROLEXUSER] as RxU ON [USERS].ID=RxU.ID_USER 
  INNER JOIN [dbo].[ROLE] as Rol ON Rol.ID=RxU.ID_ROLE
  INNER JOIN [dbo].[VIEW] as V ON V.ID_ROLE=Rol.ID 
  WHERE USERS.ID=@P_USER_ID;
END

Go

CREATE PROCEDURE [dbo].[RET_LOCALS_BYUSER_PR]
  @P_USER_ID INT
AS
BEGIN

Select L.ID, L.ID_MEMBERSHIP, L.NAME, L.STATUS, L.LOCATION, L.OPENING_HOURS, L.PHONE_NUMBER, L.EMAIL, L.DESCRIPTION, L.WEBSITE, L.PRICE_RANGE, L.CATEGORY  from dbo.[LOCAL] as L
  INNER JOIN [dbo].[USERXLOCAL] as UXL ON L.ID=UXL.ID_LOCAL 
  INNER JOIN [dbo].[USERS] as U ON U.ID=UXL.ID_USER
  WHERE U.ID=@P_USER_ID;
END

Go

CREATE PROCEDURE [dbo].[RET_ALL_PRODUCTS_BY_LOCAL_PR]
@P_ID_LOCAL INT
AS
SELECT * FROM [PRODUCT] WHERE ID_LOCAL = @P_ID_LOCAL;
GO

CREATE PROCEDURE [dbo].[CRE_LOCALXUSER_PR]
  @P_ID_USER INT,
  @P_ID_LOCAL INT
AS
  INSERT INTO [dbo].[USERXLOCAL](ID_USER, ID_LOCAL) 
  VALUES(@P_ID_USER, @P_ID_LOCAL)
GO

CREATE PROCEDURE [dbo].[LOGIN_PR]
@P_EMAIL VARCHAR(255),
@P_PASSWORD VARCHAR(255)

AS

SELECT us.ID, Rol.ID from dbo.[USERS] as us 
INNER JOIN [dbo].[ROLEXUSER] as RxU  ON  us.ID=RxU.ID_USER 
INNER JOIN [dbo].[ROLE] as Rol  ON  Rol.ID=RxU.ID_ROLE
WHERE EMAIL = @P_EMAIL AND PASSWORD = @P_PASSWORD;

GO