CREATE PROCEDURE CRE_DIRECTION_PR
	@P_ID_USER INT,
	@P_NAME VARCHAR(255),
	@P_COORDINATE_X FLOAT,
	@P_COORDINATE_Y FLOAT,
	@P_DESCRIPTION VARCHAR(255)
AS
	INSERT INTO DIRECTION(ID_USER,NAME,COORDINATE_X,COORDINATE_Y,DESCRIPTION)
	VALUES (@P_ID_USER,@P_NAME,@P_COORDINATE_X,@P_COORDINATE_Y,@P_DESCRIPTION)
GO

CREATE PROCEDURE RET_DIRECTION_user_PR
	@P_ID_USER INT
AS
	SELECT * FROM DIRECTION WHERE ID_USER=@P_ID_USER;	
GO

CREATE PROCEDURE RET_DIRECTION_PR
	@P_ID INT
AS
	SELECT * FROM DIRECTION WHERE ID=@P_ID;	
GO

CREATE PROCEDURE RET_ALL_DIRECTION_PR
AS
	select * FROM DIRECTION	
GO

CREATE PROCEDURE DEL_DIRECTION_PR
	@P_ID INT
AS
	DELETE FROM DIRECTION WHERE ID=@P_ID;	
GO
CREATE PROCEDURE UPD_ORDER_LOCATION_PR
	@P_ID INT,
	@P_ID_LOCATION INT
AS
	UPDATE ORDERS SET ID_LOCATION=@P_ID_LOCATION WHERE ID=@P_ID;
GO
