
--
--CATEGORY
-- 

--CREATE CATEGORY
CREATE PROCEDURE [dbo].[CRE_CATEGORY_PR]
	@ID VARCHAR(255),
	@P_NAME VARCHAR(255)
AS
	INSERT INTO UTILS VALUES(@ID,@P_NAME);
GO

-- DELETE CATEGORY
CREATE PROCEDURE [dbo].[DEL_CATEGORY_PR]
	@P_ID VARCHAR(255)
AS
	DELETE FROM UTILS WHERE ID=@P_ID;
GO

--RETRIVE ALL CATEGORY
CREATE PROCEDURE [dbo].[RET_ALL_CATEGORY_PR]
AS
	SELECT * FROM UTILS;
GO

--RETRIEVE CATEGORY BY ID
CREATE PROCEDURE [dbo].[RET_CATEGORY_PR]
	@P_ID VARCHAR(255)
AS
	SELECT * FROM [dbo].Utils where ID=@P_ID;
GO

--UPDATE CATEGORY
CREATE PROCEDURE [dbo].[UPD_CATEGORY_PR]
	@P_ID VARCHAR(255),
	@P_NAME VARCHAR(255)
AS
	UPDATE [dbo].[UTILS] SET ID=@P_ID, NAME=@P_NAME  WHERE ID=@P_ID;
GO

--
--ERROR 
-- 

-- CREATE ERROR
CREATE PROCEDURE [dbo].[CRE_ERROR_PR]
	@P_ID int,
	@P_NAME nvarchar(25)
AS
	INSERT INTO ERROR VALUES(@P_ID,@P_NAME);
GO

-- RETRIEVE ERROR BY ID
CREATE PROCEDURE [dbo].[RET_ERROR_PR]
	@P_ID varchar(50)
AS
	SELECT * FROM [dbo].Error where ID=@P_ID;