--CREATE DISCOUNT

CREATE PROCEDURE  [dbo].[CRE_DISCOUNT_PR]
@P_ID INT,
@P_ID_LOCAL INT,
@P_NAME VARCHAR(40),
@P_EXPIRATION_DATE DATETIME,
@P_TOTAL FLOAT,
@P_PERCENTAGE FLOAT,
@P_USAGE VARCHAR(40),
@P_STATUS VARCHAR(40)
AS
	INSERT INTO DISCOUNT VALUES(@P_ID,@P_ID_LOCAL,@P_NAME,@P_EXPIRATION_DATE,
	@P_TOTAL,@P_PERCENTAGE,@P_USAGE,@P_STATUS);

GO
--RETRIEVE DISCOUNT BY ID
CREATE PROCEDURE  [dbo].[RET_DISCOUNT_PR]
@P_ID INT
AS
	SELECT * FROM DISCOUNT WHERE @P_ID=ID;
GO


--RETRIEVE ALL DISCOUNT
CREATE PROCEDURE  [dbo].[RET_ALL_DISCOUNT_PR]
AS
	SELECT * FROM DISCOUNT;
GO

--UPDATE DISCOUNT
CREATE PROCEDURE  [dbo].[UPD_DISCOUNT_PR]
@P_ID INT,
@P_ID_LOCAL INT,
@P_NAME VARCHAR(40),
@P_EXPIRATION_DATE DATETIME,
@P_TOTAL FLOAT,
@P_PERCENTAGE FLOAT,
@P_USAGE VARCHAR(40),
@P_STATUS VARCHAR(40)
AS
	UPDATE DISCOUNT SET NAME=@P_NAME,EXPIRATION_DATE=@P_EXPIRATION_DATE,
	TOTAL=@P_TOTAL, PERCENTAGE=@P_PERCENTAGE, USAGE=@P_USAGE,
	STATUS=@P_STATUS WHERE ID=@P_ID;
GO

--DELETE DISCOUNT
CREATE PROCEDURE  [dbo].[DEL_DISCOUNT_PR]
	@P_ID INT
AS
	DELETE FROM DISCOUNT WHERE ID=@P_ID;
GO