CREATE PROCEDURE [dbo].[CR_VOTE_PR]
  @P_ID_USER INT ,
  @P_OBJECT VARCHAR(255),
  @P_TYPE VARCHAR(255),
  @P_GRADE VARCHAR(255)

AS 
INSERT INTO VOTES VALUES(@P_ID_USER, @P_OBJECT, @P_TYPE, @P_GRADE)

GO

CREATE PROCEDURE [dbo].[RET_ALL_VOTES_PR]
AS
SELECT * FROM VOTES;

GO