-- RETRIVE ALL ORDERS FINAL USER

CREATE PROCEDURE RET_ORDERS_USER_PR
	@P_Id_BUYER INT
AS
	SELECT o.ID, o.ID_BUYER, o.ID_SELLER, o.ID_DRIVER, o.ID_LOCATION,
	o.INVOICE, o.STATUS, o.START_TIME, o.END_TIME, o.DESCRIPTION, O.TYPE
	from orders o JOIN UTILS U on(o.STATUS=U.NAME)
	WHERE id_buyer=@P_Id_BUYER
GO