CREATE PROCEDURE [dbo].[CR_VOTE_PR]
  @P_ID_USER INT ,
  @P_VOTED INT,
  @P_TYPE VARCHAR(255),
  @P_GRADE FLOAT

AS 
INSERT INTO VOTES VALUES(@P_ID_USER, @P_VOTED, @P_TYPE, @P_GRADE)

GO

CREATE PROCEDURE [dbo].[RET_ALL_VOTES_PR]
AS
SELECT * FROM VOTES;

GO

CREATE PROCEDURE [dbo].[RET_VOTE_PR]
@P_ID INT
AS
SELECT * FROM VOTES WHERE ID = @P_ID;

GO