--CREATE TAX
CREATE PROCEDURE [dbo].[CRE_TAX_PR]
	
	@P_NAME VARCHAR(255),
	@P_PERCENTAGE FLOAT
AS
	INSERT INTO TAX VALUES(@P_NAME,@P_PERCENTAGE);
GO

-- DELETE TAX
CREATE PROCEDURE [dbo].[DEL_TAX_PR]
	@P_ID INT
AS
	DELETE FROM TAX WHERE ID=@P_ID;
GO

--RETRIVE ALL TAX
CREATE PROCEDURE [dbo].[RET_ALL_TAX_PR]
AS
	SELECT * FROM TAX;
GO

--RETRIEVE TAX BY ID
CREATE PROCEDURE [dbo].[RET_TAX_PR]
	@P_ID INT
AS
	SELECT * FROM [dbo].TAX where ID=@P_ID;
GO

--UPDATE TAX
CREATE PROCEDURE [dbo].[UPD_TAX_PR]
	@P_ID INT,
	@P_NAME VARCHAR(255),
	@P_PERCENTAGE FLOAT
AS
	UPDATE [dbo].[TAX] SET NAME=@P_NAME, PERCENTAGE=@P_PERCENTAGE  WHERE NAME=@P_NAME;
GO

